version: "3.9"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-tes-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      interval: 5s
      retries: 5
    restart: always

volumes:
  postgres-tes-db-volume:
